version: '3.10'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: politikontroller_app:${POLITIKONTROLLER_APP_VERSION:-latest}
    restart: always
    volumes:
    - politikontroller_app-db-data:/db_data/


volumes:
  politikontroller_app-db-data:
    name: politikontroller_app-db-data
